[package]
name = "stimpak"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[lib]
name = "stimpak"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
superiority-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
